# $FreeBSD$
#
# This Makefile is designed to have a very simpe interface to create a
# user-friendly interface to configure the options needed to build the
# world and/or the kernel, but not the options used to compile the kernel
# or the devices that will be statically linked to the kernel.

.include <src.opts.mk>
.include "${.CURDIR}/sys/conf/kern.opts.mk"
.include <src.opts.desc.mk>

# Declaration of programs and options
DIALOG?=/usr/bin/dialog
MAKE=/usr/bin/make -C ${.CURDIR}
MAKE_CONF=${MAKE} -f Makefile.config
DIALOG_OPTS=--backtitle "FreeBSD Configurator"
CHECK_LIST=--checklist "Build options" 50 80 45

# Message to show when changing the src.conf file
WARNMSG=The following options will be set because of the chosen options:

# Path to src.conf and src-env.conf, including the temporal ones.
SRCCONF?=/etc/src.conf
SRCCONF_BEFORE=${SRCCONF}
SRCCONF_DEFAULT=/dev/null
SRCCONF_CURRENT=/tmp/`echo ${SRCCONF} | tr '/' '_'`

SRC_ENV_CONF?=/etc/src-env.conf
SRC_ENV_CONF_BEFORE=${SRC_ENV_CONF}
SRC_ENV_CONF_DEFAULT=/dev/null
SRC_ENV_CONF_CURRENT=/tmp/`echo ${SRC_ENV_CONF} | tr '/' '_'`

CONFIG_OPTIONS=

# Get the main menu by gathering the categories
MAIN_MENU=
.for __cat in ${CATEGORIES}
    MAIN_MENU+= ${__cat}
.   if defined(${__cat}_DESC)
        MAIN_MENU+= ${${__cat}_DESC}
.   else
        MAIN_MENU+= ${${__cat}_DESC}
.   endif
.endfor

show_main_menu: .PHONY
	@${DIALOG} ${DIALOG_OPTS} --menu "Categories" 20 70 15 \
		${MAIN_MENU} SAVE "Save the current configuration" \
		2> /tmp/config

revert_config: .PHONY
.	if exists(${SRCCONF}.bak)
		@cp ${SRCCONF}.bak ${SRCCONF}
.	endif
.	if exists(${SRC_ENV_CONF}.bak)
		@cp ${SRC_ENV_CONF}.bak ${SRC_ENV_CONF}
.	endif

create_config_backup:
.	if exists(${SRCCONF})
		cp ${SRCCONF} ${SRCCONF}.bak
.	endif
.	if exists(${SRC_ENV_CONF})
		cp ${SRC_ENV_CONF} ${SRC_ENV_CONF}.bak
.	endif


